name: TestRegression

on:
 workflow_dispatch:
    inputs:
      environment:
        required: true
        default: "prod"
        description: "Set environment, e.g. `ENV=prod or ENV=shot`"
      arguments:
        required: false
        default: "-m regression"
        description: "pytest additional arguments, e.g. `-m regression`"

jobs:
 playwright:
    name: Regression tests
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/python:v1.41.0-jammy
    env:
      AUTH_LOGIN: ${{ secrets.AUTH_LOGIN }}
      AUTH_PASSWORD: ${{ secrets.AUTH_PASSWORD }}
      NewUserName: ${{ secrets.NEWUSERNAME }}
      NewEmail: ${{ secrets.NEWEMAIL }}
      NewPass: ${{ secrets.NEWPASS }}
    strategy:
      matrix:
        browser: [remote_chrome]
    outputs:
      env_name: ${{ steps.pytest.outputs.env_name }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: python3 -m pip install -r requirements.txt
      - name: Run tests
        id: run_tests
        run: |
          if [ "${{github.event_name}}" = "schedule" ]; then
            export args="-m smoke"
            export ENV="prod"
          else
            export ENV='${{github.event.inputs.environment}}'
            export args='${{github.event.inputs.arguments}}'
          fi
          echo "::set-output name=env_name::${ENV:-prod}"
          pytest tests/*.py ${args} --bn ${{ matrix.browser }} --alluredir=./allure-results
      - name: Deploy report to gh-pages
        uses: actions/checkout@v3
        with:
          ref: gh-pages  # Checkout gh-pages branch
        if: always()  # This step runs even if previous steps fail
      - run: |
            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"
            git add allure-report/*  # Add all report files to staging
            git commit -m "Add Allure report for ${{ github.sha }}"  # Commit with SHA
            git push origin gh-pages  # Push to gh-pages branch

