name: CI
on: [push, pull_request]
jobs:
 test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          playwright install 
      - name: Run tests
        run: |
          source venv/bin/activate
          PLAYWRIGHT_HEADLESS=1
          pytest tests/*.py --alluredir=allure-results 
      - name: Upload Allure report
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: allure-results/*
